## <font color="coral"> Intro to Pandas</font>
    
#### <font color="coral"> In this notebook we'll be looking at Scipy's Pandas library for data analysis. This notebook will briefly cover:</font>
    
- Reading in .csv or .xlsx with pandas
- Inspecting, indexing, and performing summary statistics on data
- Finding summary statistics, exploratory data analysis
- Creating new columns and modifying data
- Filtering out or dropping unwanted data
- Combining multiple data tables
    
#### <font color="coral"> Notebook usage</font>
    
This notebook is intended to be worked through top-to-bottom, feel free to change what you'd like and experiment with any ideas you have. To advance in the notebook you can click on each cell and hit the "▶️" button, or pressing "Shift-Enter/Return". Try running the cell below!

In [1]:
import pandas as pd
import numpy as np

### <font color="coral"> Pandas Intution</font>
    
Pandas is a library for examining "spreadsheet" style data. This is the general data format that Microsoft Excel and Google Sheets works with. 
    
To replicate the grid-like structure of the data within a .csv file, Pandas provides a `DataFrame` class. This class can be thought of as a **nested list or numpy nd.Array** grid object that can also be used like a python **dictionary**.

In [2]:
# Example of nested-list behavior

# Nested list
grid = np.array([
    ["Name", "Age", "Grade"],
    ["Carlos", 13, 8],
    ["Sandra", 8, 3]
])

# Can access rows or columns of a grid using an index []:
print("First data row:", grid[1])
print("Name of student in first row:", grid[1, 0])

First data row: ['Carlos' '13' '8']
Name of student in first row: Carlos

In [3]:
# Example of dictionary behavior
pokemon_2_type = {
    "Charmander" : "Fire", 
    "Squirtle" : "Water",
    "Bulbasaur" : "Grass"
}

# dictionary values can be accessed using a "key"
print("What is Charmander's type again?")
print(pokemon_2_type["Charmander"])

What is Charmander's type again?
Fire

##### When working with a pandas DataFrame:
- Want to get a column? - dictionary-like syntax, `["column_name"]`
- Want to get a row? - numpy or grid-like syntax, `[index_1, index_2]`

#### <font color="Coral"> Reading data into and viewing a DataFrame</font>
    
The primary methods of reading data from a .csv and .xlsx file are the `pd.read_csv()` and `pd.read_excel()`, respectively. In most cases, these functions have the data's `filepath` provided to them. 
    
<font color="coral"> Our practice data</font>
    
The data we will be using is volcano eruption and event data, provided publicly by [RforDataScience](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-05-12/). 

Let's look at the data now!
    1) Read in .csv data
    2) Display data within DataFrame using `display()` and `head()`

In [4]:
# Store the data into a pandas dataframe
volc_tiny = pd.read_csv("volcano_data/filtered_volcano_tiny.csv")

# See how many rows and columns you're working with. Shape -> (rows, cols)
print("Df dims:", volc_tiny.shape)

# You can display the contents
display(volc_tiny.head())

Df dims: (30, 17)

,volcano_number,volcano_name,primary_volcano_type,last_eruption_year,country,region,subregion,latitude,longitude,elevation,tectonic_settings,evidence_category,major_rock_1,population_within_5_km,population_within_10_km,population_within_30_km,population_within_100_km
0,283001,Abu,Shield(s),-6850,Japan,"Japan, Taiwan, Marianas",Honshu,34.500,131.600,641,Subduction zone / Continental crust (>25 km),Eruption Dated,Andesite / Basaltic Andesite,3597,9594,117805,4071152
1,355096,Acamarachi,Stratovolcano,Unknown,Chile,South America,"Northern Chile, Bolivia and Argentina",-23.292,-67.618,6023,Subduction zone / Continental crust (>25 km),Evidence Credible,Dacite,0,7,294,9092
2,342080,Acatenango,Stratovolcano(es),1972,Guatemala,México and Central America,Guatemala,14.501,-90.876,3976,Subduction zone / Continental crust (>25 km),Eruption Observed,Andesite / Basaltic Andesite,4329,60730,1042836,7634778
3,213004,Acigol-Nevsehir,Caldera,-2080,Turkey,Mediterranean and Western Asia,Turkey,38.537,34.621,1683,Intraplate / Continental crust (>25 km),Eruption Dated,Rhyolite,127863,127863,218469,2253483
4,321040,Adams,Stratovolcano,950,United States,Canada and Western USA,USA (Washington),46.206,-121.490,3742,Subduction zone / Continental crust (>25 km),Eruption Dated,Andesite / Basaltic Andesite,0,70,4019,393303

In [5]:
# Important to look at columns and index
print(volc_tiny.columns)
print()

print(volc_tiny.index)

Index(['volcano_number', 'volcano_name', 'primary_volcano_type',
       'last_eruption_year', 'country', 'region', 'subregion', 'latitude',
       'longitude', 'elevation', 'tectonic_settings', 'evidence_category',
       'major_rock_1', 'population_within_5_km', 'population_within_10_km',
       'population_within_30_km', 'population_within_100_km'],
      dtype='object')

RangeIndex(start=0, stop=30, step=1)

In [6]:
# Let's look at an individual column
display(volc_tiny["volcano_name"]) # can also do volc_tiny.volcano_name

# And multiple columns at once
display(volc_tiny[["volcano_name", "country"]])

0                  Abu
1           Acamarachi
2           Acatenango
3      Acigol-Nevsehir
4                Adams
5          Adatarayama
6                 Adwa
7               Afdera
8              Agrigan
9                 Agua
10         Agua de Pau
11            Aguilera
12               Agung
13                Ahyi
14                Aira
15       Akademia Nauk
16            Akagisan
17                Akan
18    Akita-Komagatake
19      Akita-Yakeyama
20         Akusekijima
21              Akutan
22               Alaid
23              Alayta
24              Alcedo
25            Ale Bagu
26                Alid
27               Aliso
28      Alligator Lake
29           Almolonga
Name: volcano_name, dtype: object

        volcano_name        country
0                Abu          Japan
1         Acamarachi          Chile
2         Acatenango      Guatemala
3    Acigol-Nevsehir         Turkey
4              Adams  United States
5        Adatarayama          Japan
6               Adwa       Ethiopia
7             Afdera       Ethiopia
8            Agrigan  United States
9               Agua      Guatemala
10       Agua de Pau       Portugal
11          Aguilera          Chile
12             Agung      Indonesia
13              Ahyi  United States
14              Aira          Japan
15     Akademia Nauk         Russia
16          Akagisan          Japan
17              Akan          Japan
18  Akita-Komagatake          Japan
19    Akita-Yakeyama          Japan
20       Akusekijima          Japan
21            Akutan  United States
22             Alaid         Russia
23            Alayta       Ethiopia
24            Alcedo        Ecuador
25          Ale Bagu       Ethiopia
26              Alid        Eritrea
27             Aliso        Ecuador
28    Alligator Lake         Canada
29         Almolonga      Guatemala

In [7]:
# Why does the first column printed look different from the second columns printed?
print(type(volc_tiny.volcano_name))
print(type(volc_tiny[["volcano_name", "country"]]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

In [8]:
# And now an individual
display(volc_tiny.iloc[0])

# and multiple rows
display(volc_tiny.iloc[0:5])

volcano_number                                                    283001
volcano_name                                                         Abu
primary_volcano_type                                           Shield(s)
last_eruption_year                                                 -6850
country                                                            Japan
region                                           Japan, Taiwan, Marianas
subregion                                                         Honshu
latitude                                                            34.5
longitude                                                          131.6
elevation                                                            641
tectonic_settings           Subduction zone / Continental crust (>25 km)
evidence_category                                         Eruption Dated
major_rock_1                                Andesite / Basaltic Andesite
population_within_5_km                                              3597
population_within_10_km                                             9594
population_within_30_km                                           117805
population_within_100_km                                         4071152
Name: 0, dtype: object

,volcano_number,volcano_name,primary_volcano_type,last_eruption_year,country,region,subregion,latitude,longitude,elevation,tectonic_settings,evidence_category,major_rock_1,population_within_5_km,population_within_10_km,population_within_30_km,population_within_100_km
0,283001,Abu,Shield(s),-6850,Japan,"Japan, Taiwan, Marianas",Honshu,34.500,131.600,641,Subduction zone / Continental crust (>25 km),Eruption Dated,Andesite / Basaltic Andesite,3597,9594,117805,4071152
1,355096,Acamarachi,Stratovolcano,Unknown,Chile,South America,"Northern Chile, Bolivia and Argentina",-23.292,-67.618,6023,Subduction zone / Continental crust (>25 km),Evidence Credible,Dacite,0,7,294,9092
2,342080,Acatenango,Stratovolcano(es),1972,Guatemala,México and Central America,Guatemala,14.501,-90.876,3976,Subduction zone / Continental crust (>25 km),Eruption Observed,Andesite / Basaltic Andesite,4329,60730,1042836,7634778
3,213004,Acigol-Nevsehir,Caldera,-2080,Turkey,Mediterranean and Western Asia,Turkey,38.537,34.621,1683,Intraplate / Continental crust (>25 km),Eruption Dated,Rhyolite,127863,127863,218469,2253483
4,321040,Adams,Stratovolcano,950,United States,Canada and Western USA,USA (Washington),46.206,-121.490,3742,Subduction zone / Continental crust (>25 km),Eruption Dated,Andesite / Basaltic Andesite,0,70,4019,393303

In [9]:
# only look at two columns for the first 5 rows?
display(volc_tiny.loc[0:5, ["volcano_name", "country"]])

      volcano_name        country
0              Abu          Japan
1       Acamarachi          Chile
2       Acatenango      Guatemala
3  Acigol-Nevsehir         Turkey
4            Adams  United States
5      Adatarayama          Japan

#### <font color="coral"> Analyzing data within your DataFrame</font>

Pandas Series support most simple statistics operations:
- `mean(), mode(), min(), max(), std(), sum()`

They also provide some useful data summaries:
- `.value_counts(), nunique()`

In [10]:
# Let's find a column and do some stats!

# Stats of population 10km of a volcano
print(volc_tiny.population_within_10_km.mean())
print(volc_tiny.population_within_10_km.max())
print(volc_tiny.population_within_10_km.min())
print(volc_tiny.population_within_10_km.std())
print(volc_tiny.population_within_10_km.sum())

27815.133333333335
287487
0
62122.50704898004
834454

In [11]:
# What types of volcanoes are present in the data?
volc_tiny.primary_volcano_type.value_counts()

Stratovolcano        17
Stratovolcano(es)     5
Caldera               3
Shield                2
Submarine             1
Volcanic field        1
Shield(s)             1
Name: primary_volcano_type, dtype: int64

In [12]:
# How many countries are represented in the data?
volc_tiny.country.nunique()

12

#### <font color="coral"> Adding and modifying data </font> 

It's possible to add new columns, rows, and to alter data already within a pandas dataframe. 

1. Add a new column to DataFrame `df` with: `df["new_column_name"] = (some value, Series, List, np.Array)`
2. Add a new row with: `df.append(new_row, inplace=True)`
3. Alter data (very conservatively) with `df.iloc[index_1, index_2] = new_val`

You can also change a column's name with `.rename()`

In [13]:
# Let's add a new column to our dataset signifying where the data came from 
display(volc_tiny.head())
volc_tiny["dataset"] = "Tiny"
display(volc_tiny.head())

,volcano_number,volcano_name,primary_volcano_type,last_eruption_year,country,region,subregion,latitude,longitude,elevation,tectonic_settings,evidence_category,major_rock_1,population_within_5_km,population_within_10_km,population_within_30_km,population_within_100_km
0,283001,Abu,Shield(s),-6850,Japan,"Japan, Taiwan, Marianas",Honshu,34.500,131.600,641,Subduction zone / Continental crust (>25 km),Eruption Dated,Andesite / Basaltic Andesite,3597,9594,117805,4071152
1,355096,Acamarachi,Stratovolcano,Unknown,Chile,South America,"Northern Chile, Bolivia and Argentina",-23.292,-67.618,6023,Subduction zone / Continental crust (>25 km),Evidence Credible,Dacite,0,7,294,9092
2,342080,Acatenango,Stratovolcano(es),1972,Guatemala,México and Central America,Guatemala,14.501,-90.876,3976,Subduction zone / Continental crust (>25 km),Eruption Observed,Andesite / Basaltic Andesite,4329,60730,1042836,7634778
3,213004,Acigol-Nevsehir,Caldera,-2080,Turkey,Mediterranean and Western Asia,Turkey,38.537,34.621,1683,Intraplate / Continental crust (>25 km),Eruption Dated,Rhyolite,127863,127863,218469,2253483
4,321040,Adams,Stratovolcano,950,United States,Canada and Western USA,USA (Washington),46.206,-121.490,3742,Subduction zone / Continental crust (>25 km),Eruption Dated,Andesite / Basaltic Andesite,0,70,4019,393303

,volcano_number,volcano_name,primary_volcano_type,last_eruption_year,country,region,subregion,latitude,longitude,elevation,tectonic_settings,evidence_category,major_rock_1,population_within_5_km,population_within_10_km,population_within_30_km,population_within_100_km,dataset
0,283001,Abu,Shield(s),-6850,Japan,"Japan, Taiwan, Marianas",Honshu,34.500,131.600,641,Subduction zone / Continental crust (>25 km),Eruption Dated,Andesite / Basaltic Andesite,3597,9594,117805,4071152,Tiny
1,355096,Acamarachi,Stratovolcano,Unknown,Chile,South America,"Northern Chile, Bolivia and Argentina",-23.292,-67.618,6023,Subduction zone / Continental crust (>25 km),Evidence Credible,Dacite,0,7,294,9092,Tiny
2,342080,Acatenango,Stratovolcano(es),1972,Guatemala,México and Central America,Guatemala,14.501,-90.876,3976,Subduction zone / Continental crust (>25 km),Eruption Observed,Andesite / Basaltic Andesite,4329,60730,1042836,7634778,Tiny
3,213004,Acigol-Nevsehir,Caldera,-2080,Turkey,Mediterranean and Western Asia,Turkey,38.537,34.621,1683,Intraplate / Continental crust (>25 km),Eruption Dated,Rhyolite,127863,127863,218469,2253483,Tiny
4,321040,Adams,Stratovolcano,950,United States,Canada and Western USA,USA (Washington),46.206,-121.490,3742,Subduction zone / Continental crust (>25 km),Eruption Dated,Andesite / Basaltic Andesite,0,70,4019,393303,Tiny

In [14]:
# Maybe we want to double up or preserve a row:
row_0 = volc_tiny.iloc[0]
print(volc_tiny.shape)
volc_tiny = volc_tiny.append(row_0)
print(volc_tiny.shape)

(30, 18)
(31, 18)

In [15]:
# Manually "correct" an incorrect cell
display(volc_tiny.iloc[2])
volc_tiny.iloc[2, -5] = 3000
display(volc_tiny.iloc[2])

volcano_number                                                    342080
volcano_name                                                  Acatenango
primary_volcano_type                                   Stratovolcano(es)
last_eruption_year                                                  1972
country                                                        Guatemala
region                                        México and Central America
subregion                                                      Guatemala
latitude                                                          14.501
longitude                                                        -90.876
elevation                                                           3976
tectonic_settings           Subduction zone / Continental crust (>25 km)
evidence_category                                      Eruption Observed
major_rock_1                                Andesite / Basaltic Andesite
population_within_5_km                                              4329
population_within_10_km                                            60730
population_within_30_km                                          1042836
population_within_100_km                                         7634778
dataset                                                             Tiny
Name: 2, dtype: object

volcano_number                                                    342080
volcano_name                                                  Acatenango
primary_volcano_type                                   Stratovolcano(es)
last_eruption_year                                                  1972
country                                                        Guatemala
region                                        México and Central America
subregion                                                      Guatemala
latitude                                                          14.501
longitude                                                        -90.876
elevation                                                           3976
tectonic_settings           Subduction zone / Continental crust (>25 km)
evidence_category                                      Eruption Observed
major_rock_1                                Andesite / Basaltic Andesite
population_within_5_km                                              3000
population_within_10_km                                            60730
population_within_30_km                                          1042836
population_within_100_km                                         7634778
dataset                                                             Tiny
Name: 2, dtype: object

#### <font color="coral"> Contrived Example, Matching Columns </font> 

Here's the scenario, you are trying to combine your current volcano dataset with a second  dataset. However, in the "evidence_category" column, this second dataset uses abbreviations instead of writing everything out:
- your dataset - new dataset
- Evidence Credible - EC
- Eruption Observed - EO
- Eruption Dated - ED
- Eruption Uncertain - EU

In [16]:
# Dedicated cell to show off pd.str magic
volc_tiny.evidence_category.str.split()

0         [Eruption, Dated]
1      [Evidence, Credible]
2      [Eruption, Observed]
3         [Eruption, Dated]
4         [Eruption, Dated]
5      [Eruption, Observed]
6      [Evidence, Credible]
7     [Evidence, Uncertain]
8      [Eruption, Observed]
9      [Evidence, Credible]
10     [Eruption, Observed]
11        [Eruption, Dated]
12     [Eruption, Observed]
13        [Eruption, Dated]
14     [Eruption, Observed]
15     [Eruption, Observed]
16    [Evidence, Uncertain]
17     [Eruption, Observed]
18     [Eruption, Observed]
19     [Eruption, Observed]
20    [Evidence, Uncertain]
21     [Eruption, Observed]
22     [Eruption, Observed]
23     [Eruption, Observed]
24     [Eruption, Observed]
25     [Evidence, Credible]
26     [Evidence, Credible]
27        [Eruption, Dated]
28     [Evidence, Credible]
29     [Eruption, Observed]
0         [Eruption, Dated]
Name: evidence_category, dtype: object

In [17]:
volc_tiny["abbrev_evidence"] = "E" + volc_tiny.evidence_category.str.split().str[1].str[0]
volc_tiny["abbrev_evidence"]

0     ED
1     EC
2     EO
3     ED
4     ED
5     EO
6     EC
7     EU
8     EO
9     EC
10    EO
11    ED
12    EO
13    ED
14    EO
15    EO
16    EU
17    EO
18    EO
19    EO
20    EU
21    EO
22    EO
23    EO
24    EO
25    EC
26    EC
27    ED
28    EC
29    EO
0     ED
Name: abbrev_evidence, dtype: object

#### <font color="coral"> Filtering unwanted data </font> 

Now we want to do some analysis without all of our data. Perhaps some of our data is poor quality or is irrelevant to the question we'd like to ask. 

The syntax for filtering data in pandas can be verbose and gets much easier with experience in python/numpy idioms. The steps are:
1. Make a "boolean" Series or DataFrame with `True` or `False` values
2. Use the boolean Series or DataFrame to filter, all the `True` values are kept

You can create a boolean Series by using regular comparison operators, `< > <= >= == !=`

If you want to keep or filter multiple values, you can use `Series.isin()`

Finally, you can negate a boolean Series or DataFrame with a `~` symbol in front.

In [18]:
# Only keep volcanoes with 100,000 or more people with 10km

# Create Boolean
display(volc_tiny.population_within_10_km.iloc[0:5])
volc_tiny.population_within_10_km.iloc[0:5] > 100000

0      9594
1         7
2     60730
3    127863
4        70
Name: population_within_10_km, dtype: int64

0    False
1    False
2    False
3     True
4    False
Name: population_within_10_km, dtype: bool

In [19]:
volc_tiny[volc_tiny.population_within_10_km > 1e5]

,volcano_number,volcano_name,primary_volcano_type,last_eruption_year,country,region,subregion,latitude,longitude,elevation,tectonic_settings,evidence_category,major_rock_1,population_within_5_km,population_within_10_km,population_within_30_km,population_within_100_km,dataset,abbrev_evidence
3,213004,Acigol-Nevsehir,Caldera,-2080,Turkey,Mediterranean and Western Asia,Turkey,38.537,34.621,1683,Intraplate / Continental crust (>25 km),Eruption Dated,Rhyolite,127863,127863,218469,2253483,Tiny,ED
9,342100,Agua,Stratovolcano,Unknown,Guatemala,México and Central America,Guatemala,14.465,-90.743,3760,Subduction zone / Continental crust (>25 km),Evidence Credible,Andesite / Basaltic Andesite,9890,114404,2530449,7441660,Tiny,EC
14,282080,Aira,Caldera,2020,Japan,"Japan, Taiwan, Marianas",Ryukyu Islands and Kyushu,31.593,130.657,1117,Subduction zone / Continental crust (>25 km),Eruption Observed,Andesite / Basaltic Andesite,4918,113874,905254,2610033,Tiny,EO
29,342040,Almolonga,Stratovolcano,1818,Guatemala,México and Central America,Guatemala,14.797,-91.519,3173,Subduction zone / Continental crust (>25 km),Eruption Observed,Dacite,91323,287487,1126942,6828403,Tiny,EO

In [20]:
# and the opposite, volcanoes with < 100000 population w/in 10km?
volc_tiny[~(volc_tiny.population_within_10_km > 1e5)]

,volcano_number,volcano_name,primary_volcano_type,last_eruption_year,country,region,subregion,latitude,longitude,elevation,tectonic_settings,evidence_category,major_rock_1,population_within_5_km,population_within_10_km,population_within_30_km,population_within_100_km,dataset,abbrev_evidence
0,283001,Abu,Shield(s),-6850,Japan,"Japan, Taiwan, Marianas",Honshu,34.500,131.600,641,Subduction zone / Continental crust (>25 km),Eruption Dated,Andesite / Basaltic Andesite,3597,9594,117805,4071152,Tiny,ED
1,355096,Acamarachi,Stratovolcano,Unknown,Chile,South America,"Northern Chile, Bolivia and Argentina",-23.292,-67.618,6023,Subduction zone / Continental crust (>25 km),Evidence Credible,Dacite,0,7,294,9092,Tiny,EC
2,342080,Acatenango,Stratovolcano(es),1972,Guatemala,México and Central America,Guatemala,14.501,-90.876,3976,Subduction zone / Continental crust (>25 km),Eruption Observed,Andesite / Basaltic Andesite,3000,60730,1042836,7634778,Tiny,EO
4,321040,Adams,Stratovolcano,950,United States,Canada and Western USA,USA (Washington),46.206,-121.490,3742,Subduction zone / Continental crust (>25 km),Eruption Dated,Andesite / Basaltic Andesite,0,70,4019,393303,Tiny,ED
5,283170,Adatarayama,Stratovolcano(es),1996,Japan,"Japan, Taiwan, Marianas",Honshu,37.647,140.281,1728,Subduction zone / Continental crust (>25 km),Eruption Observed,Andesite / Basaltic Andesite,428,3936,717078,5024654,Tiny,EO
6,221170,Adwa,Stratovolcano,Unknown,Ethiopia,Africa and Red Sea,Africa (northeastern) and Red Sea,10.070,40.840,1733,Rift zone / Intermediate crust (15-25 km),Evidence Credible,Rhyolite,101,485,18645,1242922,Tiny,EC
7,221110,Afdera,Stratovolcano,Unknown,Ethiopia,Africa and Red Sea,Africa (northeastern) and Red Sea,13.088,40.853,1250,Rift zone / Intermediate crust (15-25 km),Evidence Uncertain,Rhyolite,51,6042,8611,161009,Tiny,EU
8,284160,Agrigan,Stratovolcano,1917,United States,"Japan, Taiwan, Marianas","Izu, Volcano, and Mariana Islands",18.770,145.670,965,Subduction zone / Crustal thickness unknown,Eruption Observed,Basalt / Picro-Basalt,0,0,0,0,Tiny,EO
10,382090,Agua de Pau,Stratovolcano,1564,Portugal,Atlantic Ocean,Azores,37.770,-25.470,947,Rift zone / Oceanic crust (< 15 km),Eruption Observed,Trachyte / Trachydacite,406,17272,113131,119653,Tiny,EO
11,358062,Aguilera,Stratovolcano,-1250,Chile,South America,Southern Chile and Argentina,-50.330,-73.750,2546,Subduction zone / Continental crust (>25 km),Eruption Dated,Dacite,0,0,103,5698,Tiny,ED
12,264020,Agung,Stratovolcano,2019,Indonesia,Indonesia,Lesser Sunda Islands,-8.343,115.508,2997,Subduction zone / Continental crust (>25 km),Eruption Observed,Andesite / Basaltic Andesite,5657,76781,968381,4550176,Tiny,EO
13,284141,Ahyi,Submarine,2014,United States,"Japan, Taiwan, Marianas","Izu, Volcano, and Mariana Islands",20.420,145.030,-75,Subduction zone / Crustal thickness unknown,Eruption Dated,Andesite / Basaltic Andesite,0,0,0,0,Tiny,ED
15,300125,Akademia Nauk,Stratovolcano(es),1996,Russia,Kamchatka and Mainland Asia,Kamchatka Peninsula,53.980,159.450,1180,Subduction zone / Continental crust (>25 km),Eruption Observed,Andesite / Basaltic Andesite,3,3,615,12484,Tiny,EO
16,283130,Akagisan,Stratovolcano,Unknown,Japan,"Japan, Taiwan, Marianas",Honshu,36.560,139.193,1828,Subduction zone / Continental crust (>25 km),Evidence Uncertain,Andesite / Basaltic Andesite,961,4538,1116366,16718375,Tiny,EU
17,285070,Akan,Caldera,2008,Japan,"Japan, Taiwan, Marianas",Hokkaido,43.384,144.013,1499,Subduction zone / Continental crust (>25 km),Eruption Observed,Andesite / Basaltic Andesite,2062,2062,9756,929538,Tiny,EO
18,283230,Akita-Komagatake,Stratovolcano(es),1971,Japan,"Japan, Taiwan, Marianas",Honshu,39.761,140.799,1637,Subduction zone / Continental crust (>25 km),Eruption Observed,Basalt / Picro-Basalt,376,3864,216708,2521611,Tiny,EO
19,283260,Akita-Yakeyama,Stratovolcano,1997,Japan,"Japan, Taiwan, Marianas",Honshu,39.964,140.757,1366,Subduction zone / Continental crust (>25 km),Eruption Observed,Andesite / Basaltic Andesite,127,721,55493,3122037,Tiny,EO
20,282022,Akusekijima,Stratovolcano(es),Unknown,Japan,"Japan, Taiwan, Marianas",Ryukyu Islands and Kyushu,29.465,129.594,555,Subduction zone / Oceanic crust (< 15 km),Evidence Uncertain,Andesite / Basaltic Andesite,52,52,199,749,Tiny,EU
21,311320,Akutan,Stratovolcano,1992,United States,Alaska,Aleutian Islands,54.134,-165.986,1303,Subduction zone / Intermediate crust (15-25 km),Eruption Observed,Basalt / Picro-Basalt,0,24,233,4361,Tiny,EO
22,290390,Alaid,Stratovolcano,2018,Russia,Kuril Islands,Kuril Islands,50.861,155.565,2285,Subduction zone / Continental crust (>25 km),Eruption Observed,Basalt / Picro-Basalt,0,64,64,2887,Tiny,EO
23,221112,Alayta,Shield,1915,Ethiopia,Africa and Red Sea,Africa (northeastern) and Red Sea,12.888,40.573,1496,Rift zone / Intermediate crust (15-25 km),Eruption Observed,Basalt / Picro-Basalt,156,925,13459,330411,Tiny,EO
24,353040,Alcedo,Shield,1993,Ecuador,South America,Galapagos Islands,-0.430,-91.120,1130,Rift zone / Oceanic crust (< 15 km),Eruption Observed,Basalt / Picro-Basalt,290,290,388,10756,Tiny,EO
25,221090,Ale Bagu,Stratovolcano,Unknown,Ethiopia,Africa and Red Sea,Africa (northeastern) and Red Sea,13.512,40.631,988,Rift zone / Intermediate crust (15-25 km),Evidence Credible,Basalt / Picro-Basalt,2,919,8424,278270,Tiny,EC
26,221040,Alid,Stratovolcano,Unknown,Eritrea,Africa and Red Sea,Africa (northeastern) and Red Sea,14.880,39.920,904,Rift zone / Intermediate crust (15-25 km),Evidence Credible,Rhyolite,517,2447,25942,1216179,Tiny,EC
27,352031,Aliso,Stratovolcano,-2450,Ecuador,South America,Ecuador,-0.530,-78.000,4267,Subduction zone / Continental crust (>25 km),Eruption Dated,Andesite / Basaltic Andesite,0,0,0,0,Tiny,ED
28,320020,Alligator Lake,Volcanic field,Unknown,Canada,Canada and Western USA,Canada,60.420,-135.420,2217,Intraplate / Continental crust (>25 km),Evidence Credible,Basalt / Picro-Basalt,0,0,47,20636,Tiny,EC
0,283001,Abu,Shield(s),-6850,Japan,"Japan, Taiwan, Marianas",Honshu,34.500,131.600,641,Subduction zone / Continental crust (>25 km),Eruption Dated,Andesite / Basaltic Andesite,3597,9594,117805,4071152,Tiny,ED

In [21]:
# Only keep volcanoes for which the eruption was observed
volc_tiny[volc_tiny.evidence_category == "Eruption Observed"]

,volcano_number,volcano_name,primary_volcano_type,last_eruption_year,country,region,subregion,latitude,longitude,elevation,tectonic_settings,evidence_category,major_rock_1,population_within_5_km,population_within_10_km,population_within_30_km,population_within_100_km,dataset,abbrev_evidence
2,342080,Acatenango,Stratovolcano(es),1972,Guatemala,México and Central America,Guatemala,14.501,-90.876,3976,Subduction zone / Continental crust (>25 km),Eruption Observed,Andesite / Basaltic Andesite,3000,60730,1042836,7634778,Tiny,EO
5,283170,Adatarayama,Stratovolcano(es),1996,Japan,"Japan, Taiwan, Marianas",Honshu,37.647,140.281,1728,Subduction zone / Continental crust (>25 km),Eruption Observed,Andesite / Basaltic Andesite,428,3936,717078,5024654,Tiny,EO
8,284160,Agrigan,Stratovolcano,1917,United States,"Japan, Taiwan, Marianas","Izu, Volcano, and Mariana Islands",18.770,145.670,965,Subduction zone / Crustal thickness unknown,Eruption Observed,Basalt / Picro-Basalt,0,0,0,0,Tiny,EO
10,382090,Agua de Pau,Stratovolcano,1564,Portugal,Atlantic Ocean,Azores,37.770,-25.470,947,Rift zone / Oceanic crust (< 15 km),Eruption Observed,Trachyte / Trachydacite,406,17272,113131,119653,Tiny,EO
12,264020,Agung,Stratovolcano,2019,Indonesia,Indonesia,Lesser Sunda Islands,-8.343,115.508,2997,Subduction zone / Continental crust (>25 km),Eruption Observed,Andesite / Basaltic Andesite,5657,76781,968381,4550176,Tiny,EO
14,282080,Aira,Caldera,2020,Japan,"Japan, Taiwan, Marianas",Ryukyu Islands and Kyushu,31.593,130.657,1117,Subduction zone / Continental crust (>25 km),Eruption Observed,Andesite / Basaltic Andesite,4918,113874,905254,2610033,Tiny,EO
15,300125,Akademia Nauk,Stratovolcano(es),1996,Russia,Kamchatka and Mainland Asia,Kamchatka Peninsula,53.980,159.450,1180,Subduction zone / Continental crust (>25 km),Eruption Observed,Andesite / Basaltic Andesite,3,3,615,12484,Tiny,EO
17,285070,Akan,Caldera,2008,Japan,"Japan, Taiwan, Marianas",Hokkaido,43.384,144.013,1499,Subduction zone / Continental crust (>25 km),Eruption Observed,Andesite / Basaltic Andesite,2062,2062,9756,929538,Tiny,EO
18,283230,Akita-Komagatake,Stratovolcano(es),1971,Japan,"Japan, Taiwan, Marianas",Honshu,39.761,140.799,1637,Subduction zone / Continental crust (>25 km),Eruption Observed,Basalt / Picro-Basalt,376,3864,216708,2521611,Tiny,EO
19,283260,Akita-Yakeyama,Stratovolcano,1997,Japan,"Japan, Taiwan, Marianas",Honshu,39.964,140.757,1366,Subduction zone / Continental crust (>25 km),Eruption Observed,Andesite / Basaltic Andesite,127,721,55493,3122037,Tiny,EO
21,311320,Akutan,Stratovolcano,1992,United States,Alaska,Aleutian Islands,54.134,-165.986,1303,Subduction zone / Intermediate crust (15-25 km),Eruption Observed,Basalt / Picro-Basalt,0,24,233,4361,Tiny,EO
22,290390,Alaid,Stratovolcano,2018,Russia,Kuril Islands,Kuril Islands,50.861,155.565,2285,Subduction zone / Continental crust (>25 km),Eruption Observed,Basalt / Picro-Basalt,0,64,64,2887,Tiny,EO
23,221112,Alayta,Shield,1915,Ethiopia,Africa and Red Sea,Africa (northeastern) and Red Sea,12.888,40.573,1496,Rift zone / Intermediate crust (15-25 km),Eruption Observed,Basalt / Picro-Basalt,156,925,13459,330411,Tiny,EO
24,353040,Alcedo,Shield,1993,Ecuador,South America,Galapagos Islands,-0.430,-91.120,1130,Rift zone / Oceanic crust (< 15 km),Eruption Observed,Basalt / Picro-Basalt,290,290,388,10756,Tiny,EO
29,342040,Almolonga,Stratovolcano,1818,Guatemala,México and Central America,Guatemala,14.797,-91.519,3173,Subduction zone / Continental crust (>25 km),Eruption Observed,Dacite,91323,287487,1126942,6828403,Tiny,EO

In [22]:
# Only keep volcanoes for which eruption observed or eruption dated
volc_tiny[volc_tiny.evidence_category.isin(["Eruption Observed", "Eruption Dated"])]

,volcano_number,volcano_name,primary_volcano_type,last_eruption_year,country,region,subregion,latitude,longitude,elevation,tectonic_settings,evidence_category,major_rock_1,population_within_5_km,population_within_10_km,population_within_30_km,population_within_100_km,dataset,abbrev_evidence
0,283001,Abu,Shield(s),-6850,Japan,"Japan, Taiwan, Marianas",Honshu,34.500,131.600,641,Subduction zone / Continental crust (>25 km),Eruption Dated,Andesite / Basaltic Andesite,3597,9594,117805,4071152,Tiny,ED
2,342080,Acatenango,Stratovolcano(es),1972,Guatemala,México and Central America,Guatemala,14.501,-90.876,3976,Subduction zone / Continental crust (>25 km),Eruption Observed,Andesite / Basaltic Andesite,3000,60730,1042836,7634778,Tiny,EO
3,213004,Acigol-Nevsehir,Caldera,-2080,Turkey,Mediterranean and Western Asia,Turkey,38.537,34.621,1683,Intraplate / Continental crust (>25 km),Eruption Dated,Rhyolite,127863,127863,218469,2253483,Tiny,ED
4,321040,Adams,Stratovolcano,950,United States,Canada and Western USA,USA (Washington),46.206,-121.490,3742,Subduction zone / Continental crust (>25 km),Eruption Dated,Andesite / Basaltic Andesite,0,70,4019,393303,Tiny,ED
5,283170,Adatarayama,Stratovolcano(es),1996,Japan,"Japan, Taiwan, Marianas",Honshu,37.647,140.281,1728,Subduction zone / Continental crust (>25 km),Eruption Observed,Andesite / Basaltic Andesite,428,3936,717078,5024654,Tiny,EO
8,284160,Agrigan,Stratovolcano,1917,United States,"Japan, Taiwan, Marianas","Izu, Volcano, and Mariana Islands",18.770,145.670,965,Subduction zone / Crustal thickness unknown,Eruption Observed,Basalt / Picro-Basalt,0,0,0,0,Tiny,EO
10,382090,Agua de Pau,Stratovolcano,1564,Portugal,Atlantic Ocean,Azores,37.770,-25.470,947,Rift zone / Oceanic crust (< 15 km),Eruption Observed,Trachyte / Trachydacite,406,17272,113131,119653,Tiny,EO
11,358062,Aguilera,Stratovolcano,-1250,Chile,South America,Southern Chile and Argentina,-50.330,-73.750,2546,Subduction zone / Continental crust (>25 km),Eruption Dated,Dacite,0,0,103,5698,Tiny,ED
12,264020,Agung,Stratovolcano,2019,Indonesia,Indonesia,Lesser Sunda Islands,-8.343,115.508,2997,Subduction zone / Continental crust (>25 km),Eruption Observed,Andesite / Basaltic Andesite,5657,76781,968381,4550176,Tiny,EO
13,284141,Ahyi,Submarine,2014,United States,"Japan, Taiwan, Marianas","Izu, Volcano, and Mariana Islands",20.420,145.030,-75,Subduction zone / Crustal thickness unknown,Eruption Dated,Andesite / Basaltic Andesite,0,0,0,0,Tiny,ED
14,282080,Aira,Caldera,2020,Japan,"Japan, Taiwan, Marianas",Ryukyu Islands and Kyushu,31.593,130.657,1117,Subduction zone / Continental crust (>25 km),Eruption Observed,Andesite / Basaltic Andesite,4918,113874,905254,2610033,Tiny,EO
15,300125,Akademia Nauk,Stratovolcano(es),1996,Russia,Kamchatka and Mainland Asia,Kamchatka Peninsula,53.980,159.450,1180,Subduction zone / Continental crust (>25 km),Eruption Observed,Andesite / Basaltic Andesite,3,3,615,12484,Tiny,EO
17,285070,Akan,Caldera,2008,Japan,"Japan, Taiwan, Marianas",Hokkaido,43.384,144.013,1499,Subduction zone / Continental crust (>25 km),Eruption Observed,Andesite / Basaltic Andesite,2062,2062,9756,929538,Tiny,EO
18,283230,Akita-Komagatake,Stratovolcano(es),1971,Japan,"Japan, Taiwan, Marianas",Honshu,39.761,140.799,1637,Subduction zone / Continental crust (>25 km),Eruption Observed,Basalt / Picro-Basalt,376,3864,216708,2521611,Tiny,EO
19,283260,Akita-Yakeyama,Stratovolcano,1997,Japan,"Japan, Taiwan, Marianas",Honshu,39.964,140.757,1366,Subduction zone / Continental crust (>25 km),Eruption Observed,Andesite / Basaltic Andesite,127,721,55493,3122037,Tiny,EO
21,311320,Akutan,Stratovolcano,1992,United States,Alaska,Aleutian Islands,54.134,-165.986,1303,Subduction zone / Intermediate crust (15-25 km),Eruption Observed,Basalt / Picro-Basalt,0,24,233,4361,Tiny,EO
22,290390,Alaid,Stratovolcano,2018,Russia,Kuril Islands,Kuril Islands,50.861,155.565,2285,Subduction zone / Continental crust (>25 km),Eruption Observed,Basalt / Picro-Basalt,0,64,64,2887,Tiny,EO
23,221112,Alayta,Shield,1915,Ethiopia,Africa and Red Sea,Africa (northeastern) and Red Sea,12.888,40.573,1496,Rift zone / Intermediate crust (15-25 km),Eruption Observed,Basalt / Picro-Basalt,156,925,13459,330411,Tiny,EO
24,353040,Alcedo,Shield,1993,Ecuador,South America,Galapagos Islands,-0.430,-91.120,1130,Rift zone / Oceanic crust (< 15 km),Eruption Observed,Basalt / Picro-Basalt,290,290,388,10756,Tiny,EO
27,352031,Aliso,Stratovolcano,-2450,Ecuador,South America,Ecuador,-0.530,-78.000,4267,Subduction zone / Continental crust (>25 km),Eruption Dated,Andesite / Basaltic Andesite,0,0,0,0,Tiny,ED
29,342040,Almolonga,Stratovolcano,1818,Guatemala,México and Central America,Guatemala,14.797,-91.519,3173,Subduction zone / Continental crust (>25 km),Eruption Observed,Dacite,91323,287487,1126942,6828403,Tiny,EO
0,283001,Abu,Shield(s),-6850,Japan,"Japan, Taiwan, Marianas",Honshu,34.500,131.600,641,Subduction zone / Continental crust (>25 km),Eruption Dated,Andesite / Basaltic Andesite,3597,9594,117805,4071152,Tiny,ED

#### <font color="coral"> Not covered but still important </font>
- `.dropna()` more info [here](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html)

#### <font color="coral"> Combining multiple dataframes </font> 

Finally, let's practice combining different dataframes together. It might be the case that a `.csv`'s data is stored over multiple files, or two `.csv` files contain related data and it would be convenient to merge them together. 

Different "split" scenarios require combining on different axes, which are specified as arguments to `pd.concat()`.

##### 1. Columns of a DataFrame are split across 2 files:

In this first example, extra data about a volcano's geologic composition is stored in a separate file, `rock_type_tiny.csv`. 

This data has the same number of rows as `filtered_volcano_tiny.csv`. As such, we will combine the DataFrames horizontally, using `axis=1`.

In [23]:
# read in both dataframes
volc = pd.read_csv("volcano_data/filtered_volcano_tiny.csv")
rocks = pd.read_csv("volcano_data/rock_type_tiny.csv")

print(volc.shape)
print(rocks.shape)

combined_horizontal = pd.concat([volc, rocks], axis=1)
print(combined_horizontal.shape)
combined_horizontal.head()

(30, 17)
(30, 9)
(30, 26)

,volcano_number,volcano_name,primary_volcano_type,last_eruption_year,country,region,subregion,latitude,longitude,elevation,...,population_within_100_km,major_rock_2,major_rock_3,major_rock_4,major_rock_5,minor_rock_1,minor_rock_2,minor_rock_3,minor_rock_4,minor_rock_5
0,283001,Abu,Shield(s),-6850,Japan,"Japan, Taiwan, Marianas",Honshu,34.500,131.600,641,...,4071152,Basalt / Picro-Basalt,Dacite,,,,,,,
1,355096,Acamarachi,Stratovolcano,Unknown,Chile,South America,"Northern Chile, Bolivia and Argentina",-23.292,-67.618,6023,...,9092,Andesite / Basaltic Andesite,,,,,,,,
2,342080,Acatenango,Stratovolcano(es),1972,Guatemala,México and Central America,Guatemala,14.501,-90.876,3976,...,7634778,Dacite,,,,Basalt / Picro-Basalt,,,,
3,213004,Acigol-Nevsehir,Caldera,-2080,Turkey,Mediterranean and Western Asia,Turkey,38.537,34.621,1683,...,2253483,Dacite,Basalt / Picro-Basalt,Andesite / Basaltic Andesite,,,,,,
4,321040,Adams,Stratovolcano,950,United States,Canada and Western USA,USA (Washington),46.206,-121.490,3742,...,393303,Basalt / Picro-Basalt,,,,Dacite,,,,

##### 2. Rows of a dataframe are split across multiple files. 

In this case, there are hundreds of more volcanoes within our dataset than the original 30 we've been examining. We can stack these DataFrames on top of one another, using `pd.concat(axis=0)`.

In [24]:
tiny = pd.read_csv("volcano_data/filtered_volcano_tiny.csv")
remaining = pd.read_csv("volcano_data/filtered_volcano.csv")

print(tiny.shape)
print(remaining.shape)

complete_dataset = pd.concat([tiny, remaining], axis=0)
print(complete_dataset.shape)

(30, 17)
(928, 17)
(958, 17)

##### 3. Data is shared between two datasets, want to combine them. 

The `merge` function is used to combine multiple datasets that contain similar data. For this example, we will be using the `filtered_events_tiny.csv`, which contains volcanic events associated with each volcano. The two tables share both `volcano_name` and `volcano_id` columns to facilitate the merge. 

A merge is made by calling `.merge()` on one dataset. The dataset to the left of the `.merge()` call is the "left" DataFrame and the DataFrame within the `.merge()` call is the "right" DataFrame. 

To make things even more fun, there are 4 types of merge:
1. `left`, keep all values in the 'left' dataframe, remove 'right' values that don't match
2. `right` keep all values in the 'right' DataFrame, remove 'left' values that don't match
3. `outer` keep all values, akin to a set union operator
4. `inner` keep only values that appear in both datasets, akin to a set intersetion operator

In [25]:
# let's look at events and volcanos
volcanos = pd.read_csv("volcano_data/filtered_volcano.csv")
events = pd.read_csv("volcano_data/filtered_events.csv")

print(volcanos.shape)
print(events.shape)

print(volcanos.columns)
print(events.columns)

print(events.columns[events.columns.isin(volcanos.columns)])

(928, 17)
(19204, 10)
Index(['volcano_number', 'volcano_name', 'primary_volcano_type',
       'last_eruption_year', 'country', 'region', 'subregion', 'latitude',
       'longitude', 'elevation', 'tectonic_settings', 'evidence_category',
       'major_rock_1', 'population_within_5_km', 'population_within_10_km',
       'population_within_30_km', 'population_within_100_km'],
      dtype='object')
Index(['volcano_number', 'volcano_name', 'eruption_number',
       'eruption_start_year', 'event_number', 'event_type', 'event_remarks',
       'event_date_year', 'event_date_month', 'event_date_day'],
      dtype='object')
Index(['volcano_number', 'volcano_name'], dtype='object')

In [26]:
# left merge, keep all volcanoes, throw away unmatched events
combined_left = volcanos.merge(events, on="volcano_number", how="left")
combined_left.shape

(16558, 26)

In [27]:
# left merge, keep all volcanoes, throw away unmatched events
combined_right = volcanos.merge(events, on="volcano_number", how="right")
combined_right.shape

(19204, 26)

In [28]:
# left merge, keep all volcanoes, throw away unmatched events
combined_outer = volcanos.merge(events, on="volcano_number", how="outer")
combined_outer.shape

(19787, 26)

In [29]:
# left merge, keep all volcanoes, throw away unmatched events
combined_inner = volcanos.merge(events, on="volcano_number", how="inner")
combined_inner.shape

(15975, 26)

#### <font color="coral"> Saving your dataframe </font>
- `.to_csv(filepath)` or `.to_excel(filepath)` 

Finally, after you've done your manipulations, you can save your DataFrame locally. 

To avoid headaches in the future, pass in the `index=False` argument.

In [30]:
volc_tiny.to_csv("modified_tiny_volc.csv", index=False)

#### <font color="coral"> Saving what you've done here <f>